### Get groups

GET   http://localhost:3000/groups HTTP/1.1
Authorization: ali:ali

### List groups

POST  http://localhost:3000/groups HTTP/1.1
content-type: application/json
Authorization: ali:ali

{
    "name": "test",
    "usernames": ["ali","vali","bali"]
}

### Add expense

POST  http://localhost:3000/expenses HTTP/1.1
content-type: application/json
Authorization: ali:ali

{
    "title": "test",
    "amount": 10,
    "payerUsername": "bali",
    "groupName": "test"
}

### Get all expenses

GET   http://localhost:3000/expenses HTTP/1.1
Authorization: ali:ali

###

GET  http://localhost:3000/groups/test/balance HTTP/1.1
Authorization: ali:ali